title: "Florin"
author: "Florin WÃ¶ginger"
copyright: "2024"
description: "My Personal Website"
avatar: "images/avatar.jpg"
menu_item_separator: "|"
favicon: "favicons/"
describeme: ["Student.", "Coder.", "Mate Addict :)"]

homepage:
  - "about"


singleDateFormat: "2006-02-01"
indexDateFormat: "2006-02-01"
listDateFormat: "2006-02-01"


style:
  darkestColor: "#252130"
  darkColor: "#353b43"
  lightColor: "#ebeeff"
  lightestColor: "#ffffff"
  primaryColor: "#c75c5c"


social:
  "GitHub":
    icon: "github"
    title: "GitHub"
    url: "https://github.com/spizzl"
  "Email":
    icon: "mail"
    title: "My E-mail"
    url: "mailto:florin@woeginger.de"
  "Mastadon":
    icon: "twitter"
    title: "Mastodon"
    url: "https://infosec.exchange/@fuzzywood"
