baseURL = 'florin.woeginger.de'
languageCode = 'en-us'
title = 'Fuzzywood'
theme = "m10c"
authour = "Fuzzywood"
description = "<3 hacking"
[[menu.main]]
  identifier = "tags"
  name = "tags"
  url = "/tags/"
[params]
  description = ""
  difficulty = ""
  images = ['images/default-cover.png']
