baseURL = 'florin.woeginger.de'
languageCode = 'en-us'
title = 'Fuzzywoods Blogs'
theme = "m10c"
authour = "Fuzzywood"
description = "We <3 hacking"
[[menu.main]]
  identifier = "tags"
  name = "tags"
  url = "/tags/"
[params]
  short_desc = ""
  difficulty = ""
